# Generated by Django 4.1.7 on 2023-03-28 14:20

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mod', models.BooleanField(default=False)),
                ('is_nUser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('coins_scored', models.IntegerField(blank=True, default=100, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('teacherurl', models.CharField(blank=True, max_length=300, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='subImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('mod', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, null=True)),
                ('file', models.FileField(upload_to='notes/')),
                ('status', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('typeN', models.CharField(blank=True, choices=[('Assignment', 'Assignment'), ('Experiment', 'Experiment'), ('Notes', 'Notes'), ('ReferenceBook', 'Reference Book'), ('LectureSlides', 'Lecture Slides'), ('PYQ', 'PYQ')], max_length=50, null=True)),
                ('docid', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sub', unique=True)),
                ('nDetail', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buy', models.ManyToManyField(related_name='buy_notes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='notes_like', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drfApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfApp.subject')),
            ],
        ),
    ]
