# Generated by Django 4.1.7 on 2023-04-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfApp', '0002_comment_cmntreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmntreply',
            old_name='frR',
            new_name='fromUser',
        ),
        migrations.RenameField(
            model_name='cmntreply',
            old_name='cmtRply',
            new_name='replyTo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='fromU',
            new_name='fromUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='toU',
            new_name='toUser',
        ),
    ]
